# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"albertaC19": "00_webscraper.ipynb",
         "calculate_doublingtimes_region": "01_analyses.ipynb"}

modules = ["webscraper.py",
           "analyses.py"]

doc_url = "https://tyleracorn.github.io/covid_alberta/"

git_url = "https://github.com/tyleracorn/covid_alberta/tree/master/"

def custom_doc_links(name): return None
